{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  labels:
    {{- include "paxel.labels" . | nindent 4 }}
data:
  {{- range .Values.configmap.configFile }}
  {{ .name }}: |-
{{ .file | indent 4 }}
  {{- end }}
{{ .Values.configmap.configEnv.file | indent 4 }}
{{- end }}
