{{- if and .Values.cronJob.enabled .Values.cronJob.config }}
{{- range .Values.cronJob.config }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "paxel.fullname" $ }}-{{ .name }}
spec:
  schedule: "{{ .schedule }}"
  suspend: "{{ .suspend }}"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "paxel.labels" $ | nindent 12 }}
        spec:
          containers:
          - name: {{ include "paxel.fullname" $ }}-{{ .name }}
            image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag }}"
            imagePullPolicy: IfNotPresent
            {{- if .command }}
            command:
              {{- toYaml .command | nindent 14 }}
            {{- end }}
            {{- if .args }}
            args:
              {{- toYaml .args | nindent 14 }}
            {{- end }}
            {{- with .volumeMounts }}
            volumeMounts:
              {{- toYaml . | nindent 14 }}
            {{- end }}
          restartPolicy: OnFailure
          {{- if $.Values.cronJob.volumes.enabled }}
          {{- with $.Values.cronJob.volumes.config }}
          volumes:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- end }}
          {{- if $.Values.cronJob.nodeSelector.enabled -}}
          {{- with $.Values.cronJob.nodeSelector.config }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- end }}
          {{- if $.Values.cronJob.tolerations.enabled -}}
          {{- with $.Values.cronJob.tolerations.config }}
          tolerations:
            {{- toYaml . | nindent 10 }}
          {{- end }}
          {{- end }}
---
{{- end }}
{{- end }}

