apiVersion: v1
kind: Service
metadata:
  name: {{ include "paxel.fullname" . }}
  labels:
    {{- include "paxel.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    {{- if .Values.service.extraPorts.enabled -}}
    {{- with .Values.service.extraPorts.config }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "paxel.selectorLabels" . | nindent 4 }}
